account/urls.py
from django.conf.urls import url
from . import views

app_name='account'
urlpatterns = [
    url(r'^login/$',views.user_login,name="user_login"),
    # url(r'(?P<article_id>\d)/$',views.blog_article,name="blog_detail"),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
    url(r'^$',views.blog_title,name="blog_title"),
    url(r'(?P<article_id>\d)/$',views.blog_article,name="blog_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
class BlogArticles(models.Model):
    title =models.CharField(max_length=300)
    author = models.ForeignKey(User,related_name="blog_posts",on_delete='CASCADE')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

account/forms.py
from django import forms




class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import  authenticate,login
from .forms import LoginForm
# Create your views here.

def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user:
                login(request,user)
                return HttpResponse("welcome,you have been successfull")
            else:
                return HttpResponse("sorry,you password is not right")
        else:            return HttpResponse("invalid login")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request,"account/login.html",{"form":login_form})

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import BlogArticles

# Create your views here.

def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request,"blog/titles.html",{"blogs":blogs})

def blog_article(request,article_id):
    # article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles,id=article_id)
    pub = article.publish
    return render(request,"blog/content.html",{"article":article,"publish":pub})

blog/templates/blog/content.html
{% extends "base.html" %}

{% block title %}blog article{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row1">
    <div class="col-xs-12 col-md-8">
        <p class="text-center"><span>{{ article.author.username }}</span><span style="margin-left: 20px">{{ publish }}</span> </p>
        <div>{{ article.body }}</div>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>跟老齐学： www.itdi忏肝.com</p>
        <img width="200px" src="https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1183057007,4270556535&fm=26&gp=0.jpg">
    </div>
</div>
{% endblock %}

blog/templates/blog/titles.html
{% extends "base.html" %}
{% block title %}blog titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>我的博客</h1>
</div>
<div class＝"row">
	<div class="col-xs-12 col-md-8">
	<ul>
	{% for blog in blogs %}
        <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
	{% endfor %}
	</ul>
	</div>
	<div class="col-xs-6 col-md-4">
	<h2>广告</h2>
	<p>跟老齐学： www.itdi忏肝.com</p>
	 <img width="200px" src="https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1183057007,4270556535&fm=26&gp=0.jpg">
	</div>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=l">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
</head>
<body>
{% include "header.html" %}
<div class="container">
    {% block content %}{% endblock %}
</div>
{% include "footer.html" %}
{% block javascript %}{% endblock %}
</body>
</html>

templates/blog/content.html
{% extends "base.html" %}

{% block title %}blog article{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row1">
    <div class="col-xs-12 col-md-8">
        <p class="text-center"><span>{{ article.author.username }}</span><span style="margin-left: 20px">{{ publish }}</span> </p>
        <div>{{ article.body }}</div>
    </div>
    <div class="nav navbar-nav navbar-right">
        <h2>广告</h2>
        <p>跟老齐学： www.itdi忏肝.com</p>
        <img width="200px" src="https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1183057007,4270556535&fm=26&gp=0.jpg">
    </div>
</div>
{% endblock %}

templates/blog/titles.html
{% extends "base.html" %}
{% block title %}blog titles{% endblock %}
{% block content %}
<div class="row1 text-center vertical-middle-sm">
    <h1>我的博客</h1>
</div>
<div class＝"row">
	<div class="col-xs-12 col-md-8">
	<ul>
	{% for blog in blogs %}
        <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
	{% endfor %}
	</ul>
	</div>
	<div align="right">
	<h2>广告</h2>
	<p>跟老齐学： www.itdi忏肝.com</p>
	 <img width="200px" src="https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1183057007,4270556535&fm=26&gp=0.jpg">
    </div>
</div>
{% endblock %}

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.htaonet.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.baidu.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>
        </div>
        <div>
            <ul class="navbar navbar-nav" role="navigation" >
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">LOGIN</a> </li>
            </ul>
        </div>
    </nav>
</div>